### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by huayanYu** [blacklabelops/crowd#17]
```shell
docker run \
--name crowd \
-p 8095:8095 \
-v /etc/localtime:/etc/localtime \
-d blacklabelops/crowd

#Then I use docker logs-f crowd
#I can keep getting the flowing exception
02:21:14.601 SEVERE [localhost-startStop-6] org.apache.catalina.startup.HostConfig.deployDescriptor Error deploying configuration descriptor [/opt/crowd/apache-tomcat/conf/Catalina/localhost/demo.xml]
 java.io.FileNotFoundException: /opt/crowd/apache-tomcat/conf/Catalina/localhost/demo.xml (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:579)
        at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1842)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
28-Feb-2018 02:21:14.602 SEVERE [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.startup.HostConfig.deployDescriptors Error waiting for multi-thread deployment of context descriptors to complete
 java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:546)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:439)
        at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1632)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:314)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
        at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1164)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1388)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1392)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1360)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:640)
        at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1842)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 more

```

However i can use crowd normally,So it is not a big exception.

**Comment by blacklabelops** [comment]
It's annoying and fills the log file with garbage. I will take a look at it.

**Comment by blacklabelops** [comment]
Removed installation routine for demo context. Demos doesn't seem to be available in the latest crowd release.
